baseURL: 'http://www.andvari.net/'
languageCode: 'en-us'
title:  "Dave O'Connor"
theme: 'PaperMod'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-P97PTGWKVL

minify:
  disableXML: true
  minifyOutput: true

params:
 env: production # to enable google analytics, opengraph, twitter-cards and schema.
 title: "Dave O'Connor"
 description: "Dave O'Connor"
 keywords: [Portfolio, PaperMod]
 author: Me
 # author: ["Me", "You"] # multiple authors
 DateFormat: "January 2, 2006"
 defaultTheme: auto # dark, light
 disableThemeToggle: false

 ShowReadingTime: true
 ShowShareButtons: true
 ShowPostNavLinks: true
 ShowBreadCrumbs: true
 ShowCodeCopyButtons: false
 ShowWordCount: true
 ShowRssButtonInSectionTermList: true
 UseHugoToc: true
 disableSpecial1stPost: false
 disableScrollToTop: false
 comments: false
 hidemeta: false
 hideSummary: false
 showtoc: false
 tocopen: false

 assets:
   # disableHLJS: true # to disable highlight.js
   # disableFingerprinting: true
   #favicon: "<link / abs url>"
   #favicon16x16: "<link / abs url>"
   #favicon32x32: "<link / abs url>"
   #apple_touch_icon: "<link / abs url>"
   #safari_pinned_tab: "<link / abs url>"

 label:
   text: "Home"
   icon: /apple-touch-icon.png
   iconHeight: 35

 # profile-mode
 profileMode:
   enabled: true # needs to be explicitly set
   title: Dave O'Connor
   subtitle: "Engineering Leader, Coach, Human"
   imageUrl: "/images/mysteriousd.png"
   imageWidth: 120
   imageHeight: 120
   imageTitle: my image
   buttons:
     - name: Profile
       url: https://log.andvari.net/pages/about.html
     - name: Log
       url: https://log.andvari.net/

 socialIcons:
   - name: mastodon
     url: "https://mastodon.ie/@gerrowadat"
   - name: twitter
     url: "https://twitter.com/gerrowadat"
   - name: github
     url: "https://github.com/gerrowadat"
   - name: linkedin
     url: "https://www.linkedin.com/in/gerrowadat/"
   - name: instagram
     url: "https://www.instagram.com/gerrowadat"


 analytics:
   google:
     SiteVerificationTag: "XYZabc"

 cover:
   hidden: true # hide everywhere but not in structured data
   hiddenInList: true # hide on list pages and home
   hiddenInSingle: true # hide on single page

 editPost:
   URL: "https://github.com/andvarienterprises/www.andvari.net/content"
   Text: "Suggest Changes" # edit text
   appendFilePath: true # to append file path to Edit link

menu:
  main:
    - identifier: profile
      name: profile
      url: https://log.andvari.net/pages/about.html
      weight: 10
    - identifier: log 
      name: log
      url: https://log.andvari.net
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
