name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jakejarvis/hugo-build-action@v0.111.3
      with:
        args: --minify --buildDrafts
    - id: 'google-auth'
      uses: 'google-github-actions/auth@v2.1.3'
      with:
        service_account: 'andvarinet-web-writer@awaylab.iam.gserviceaccount.com'
        credentials_json: ${{ secrets.GCLOUD_JSON_KEY }}
    - id: 'upload-files'
      uses: 'google-github-actions/upload-cloud-storage@v2.1.1'
      with:
        path: 'public'
        destination: 'web-content.www.andvari.net'
        parent: false

